name: inceptor_genesis_node
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  pointycastle: ^4.0.0
  convert: ^3.1.2
  crypto: ^3.0.6
  web_socket_channel: ^3.0.3
  json_annotation: ^4.9.0
  # sqlite3: ^2.1.0
  http: ^1.4.0
  # path_provider: ^2.1.0 # need flutter
  # device_info_plus: ^9.1.0 # need flutter
  inceptor_genesis:
    path: ../inceptor_genesis

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
